misc: Create test database for nightly tests
Signed-off-by: Frediano Ziglio <freddy77@gmail.com>

diff --git a/misc/freetds_autobuild b/misc/freetds_autobuild
--- a/misc/freetds_autobuild
+++ b/misc/freetds_autobuild
@@ -176,6 +176,12 @@ grab_logs() {
 	done >> logs/log.txt
 }
 
+create_test_db() {
+	# create test database, ignore failure, possibly already created
+	echo "Creating database..."
+	echo -e 'CREATE DATABASE freetds_test\ngo\nbye\n' | ./src/apps/tsql -S $tSRV -U "$tUID" -P "$tPWD" || true
+}
+
 generic_test() {
 	trap 'echo Error $? at line $LINENO' ERR
 	local dir="$1" pwd_file="$2"
@@ -183,6 +189,7 @@ generic_test() {
 	WORKDIR=$PWD
 	set_pwd_file $ROOT/$pwd_file
 	init_log
+	create_test_db
 	./misc/test-auto.sh --no-build >> logs/log.txt
 	grab_logs
 	cd logs
@@ -197,6 +204,7 @@ test1() {
 	trap 'echo Error $? at line $LINENO' ERR
 cd test1
 WORKDIR=$PWD
+create_test_db
 ./misc/test-auto.sh --no-build --no-header >> logs/log.txt
 grab_logs
 
@@ -315,7 +323,7 @@ test_mssql2000() {
 	cd test5
 	./misc/grabcov -o pool.cov_info -- ./src/pool/tdspool msde &> /dev/null &
 	pid_pool=$!
-	sleep 0.5
+	sleep 5
 	pid_pool=$(pgrep -P $pid_pool tdspool)
 	cd ..
 	# do tests with mssql 2000
